# Generated by Django 6.0.4 on 2026-05-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_luminaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('posicao', models.CharField(max_length=50)),
                ('jogador_ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
